# Generated by Django 3.1.2 on 2020-10-23 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0003_profilefeeditemlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilefeeditemlike',
            name='feed_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='profiles_api.profilefeeditem'),
        ),
    ]
